export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const RESET_SUCCESS="RESET_SUCCESS";
export const RESET_FAIL="RESET_FAIL";
export const UPDATE_SUCCESS="UPDATE_SUCCESS";
export const UPDATE_FAIL="UPDATE_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const SET_MESSAGE_NAME = "SET_MESSAGE_NAME";
export const SET_MESSAGE_EMAIL = "SET_MESSAGE_EMAIL";
export const SET_MESSAGE_PASSWORD = "SET_MESSAGE_PASSWORD";
export const SET_MESSAGE_CONFIRM = "SET_MESSAGE_CONFIRM";
export const SET_MESSAGE_CHECKED = "SET_MESSAGE_CHECKED";

